version: '3'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "82:80"
    volumes:
      - .:/code
    environment:
      DEBUG: 'True'
